### ISSUE TITLE
Error Generating Map

### ISSUE THREAD

**Issue by WolfByte01** [LegoFigure11/RaidCrawler#170] opened 2023-09-24 05:14 UTC
**Describe the bug**
I'll randomly Get error saying "Error generating map". When you click okay the crawling continues without issues.
I do not get this error on my Violet saves.

**To Reproduce**
the steps to reproduce the behavior:
1. Crawl on a Scarlet Save (Completed Save file) (Works fine on all my violet saves)
2. See error (Happens at random times)
![Screenshot 2023-09-23 221324](https://github.com/LegoFigure11/RaidCrawler/assets/121729607/8389b814-51f1-4467-a550-746f8bc46841)

**Additional context**
Works fine on a low progress scarlet save.

**Comment by LegoFigure11** [comment] 2023-09-24 05:15
Duplicate of #163

**Closed** 2023-09-24 05:15 UTC
Labels: bug

**Comment by WolfByte01** [comment] 2023-09-24 05:17
> Duplicate of #163

Oh I'm blind didnt see that! Sorry!
