### ISSUE TITLE
A suggestion for switch-lite

### ISSUE THREAD

**Issue by Inforen2** [LegoFigure11/RaidCrawler#22] opened 2022-12-01 18:49 UTC
Is it possible to change the remote sensing pull-down mode to "key: Home*1, Down*1, Right *5, A, down*15, A, down*4, A*1, down*2, A*1, Right *2, Up*1, Right *3, A*1, Home*1, Home*1", and adjust the time delay between keys to adapt to the switch-lite?

**Comment by LegoFigure11** [comment] 2022-12-01 21:15
Duplicate of #7, fix will be live in the next release

**Closed by LegoFigure11** 2022-12-01 21:15 UTC
